name: studymate
description: Study Mate is a system to help students with medical attention with their study, leisure and social schedules. This system will bring the students, parents and doctors together so that the students’ problems are handled efficiently.We are using cross platform because this system will be on android, ios and web,Weekly and monthly reports will be sent to parents and doctors.Since the schedules are managed according to student performance and interests students will not get bored with their studies.We have included the reward system to encourage students to complete their activities successfully within the given period of time.To decrease students’ stress levels we provide them activities such as listening to music,meditation etc

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.4.0+9
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9
  firebase_auth: 0.14.0+2
  firebase_messaging: ^5.1.6
  firebase_storage: ^3.0.6
  cloud_functions: 0.4.1+1
  firebase_remote_config: 0.2.0+7
  google_sign_in: ^4.0.7
  charts_flutter: ^0.8.1
  font_awesome_flutter: ^8.2.0
  flutter_screenutil: ^0.4.2
  carousel_slider: ^0.0.4
  googleapis: ^0.54.0
  intl:
  image_picker:
  flare_flutter: ^1.5.8
  path_provider: 
  flutter_slidable: ^0.5.3
  percent_indicator: ^2.1.1
  flutter_datetime_picker:
  fab_circular_menu: ^0.1.1
  flushbar: ^1.9.1
  flutter_local_notifications: ^0.8.4
  progress_dialog:
  syncfusion_flutter_charts: ^17.3.14
  shared_preferences: ^0.5.3
  dash_chat: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.7.2+1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/minion.png
    - assets/images/kids.png
    - assets/images/user.png
    - assets/images/home.png
    - assets/images/daily.png
    - assets/images/chat.png
    - assets/images/profile.png
    - assets/images/appointment.png
    - assets/images/subject.png
    - assets/images/weekly.png
    - assets/images/activities.png
    - assets/images/leisure.png
    - assets/images/speaking.jpg
    - assets/images/swimming.jpg
    - assets/animations/MultiOptionButton.flr
    - assets/animations/tiger.flr

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Bebas
  #     fonts:
  #       - asset: assets/fonts/bebas_regular.otf
  #       - asset: assets/fonts/bebas_bold.otf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/poppins_regular.ttf
  #       - asset: assets/fonts/poppins_bold.ttf
  #         weight: 700
  #  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
